### ISSUE TITLE
run pipeline for one sample

### ISSUE THREAD

**Issue by icanwinwyz** [MarWoes/wg-blimp#13]
Thanks for developing such great tool for WGBS data analysis.

It seems mandatory to include two groups of samples to invoke the pipeline. But what if I have only one sample, how can I run the pipeline? Thanks.

**Comment by MarWoes** [comment]
Hi, Thanks for reaching out!

wg-blimp was designed to primarily use grouping information for DMR calling. However, with some changes to its configuration it is possible to run the pipeline for one sample only.

If you use the command to create a configuration file as follows (adapted to the example in our tutorial):
`wg-blimp create-config --cores-per-job=4 fastq/ chr22.fasta blood1 blood1 results-from-config wg-blimp-config.yaml`

This will create a configuration file with only your sample included. You can then edit the resulting yaml file as follows:

- Set the `samples` configuration parameter to only your sample
- Remove `dmr/annotated-dmrs.csv` from list of `target_files` paarameter (this will skip DMR calling)

I think it might be possible to change wg-blimp's CLI interface to include this use case where DMR calling is not wanted and only one sample exist (or multiple samples without any group for segmentation only).

Don't hesitate to reach out again if this workaround did not resolve the issue.

Best,
Marius

**Comment by MarWoes** [comment]
I'll close this issue due to inactivity. Feel free to re-open if necessary :)
