### ISSUE TITLE
How to provide --latency-wait flag? Is this the problem?

### ISSUE THREAD

**Issue by ebprideaux** [MarWoes/wg-blimp#16]
Hi,

I am trying to run wg-bimp on a HPC managed by slurm.  Yesterday, I tried to submit this job and it would immediately error out with:

> Submitted job 13 with external jobid 'Submitted batch job 34588715'.
> Waiting at most 3 seconds for missing files.
> MissingOutputException in line 55 of /home/barton/bin/anaconda3/lib/python3.7/site-packages/snakemake_wrapper/Snakefile:
> Job Missing files after 3 seconds:
> /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.first.txt
> /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.second.txt
> This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
> Job id: 20 completed successfully, but some output files are missing. 20
> Removing output files of failed job find_fqs since they might be corrupted:
> /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.first.txt, /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.second.txt
> Waiting at most 3 seconds for missing files.
> MissingOutputException in line 55 of /home/barton/bin/anaconda3/lib/python3.7/site-packages/snakemake_wrapper/Snakefile:
> Job Missing files after 3 seconds:
> /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.first.txt
> /resource3/data/WGBS/Processed_wg-blimp/results-from-config/raw/Control_S1.second.txt
> This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
> Job id: 20 completed successfully, but some output files are missing. 20

I ran the same command this morning and it went through, but seemed to hang up (no slurm jobs in squeue but Python script had not been killed in the tmux tab).  I eventually killed the job and tried to re-run with the same command.  Now I am back to the same error code as above.

I have tried to add the --latency-wait flag in multiple locations, but it has resulted in a unknown flag error each time.  Can you provide how to submit this flag?  Is there another solution?

My job submission command:
`-bash-4.2$ wg-blimp run-snakemake-from-config --cores 32 --nodes 2 --cluster "sbatch -p compute0 --nodes=1 --ntasks-per-node 32 --time 01:00:00" wg-blimp-config.yaml`

My config file:
[wg-blimp-config.yaml.txt](https://github.com/MarWoes/wg-blimp/files/7421360/wg-blimp-config.yaml.txt)

My csv file:
[wg-blimp-csv.csv](https://github.com/MarWoes/wg-blimp/files/7421363/wg-blimp-csv.csv)

Thank you!

**Comment by MarWoes** [comment]
Hi there,
Thanks for reaching out! Currently, not all parameters are forwarded to Snakemake's API, but as you pointed out, it would make sense to allow more parameters to be forwarded to prevent such issues.
I'll look into it!
Best,
Marius
