### ISSUE TITLE
Reference genome

### ISSUE THREAD

**Issue by freedomq8** [MarWoes/wg-blimp#4]
Hi there, 

Just want to make sure if i should use the human reference genome that is bisulfitated or the regular one or i shouldnt include any ?

Thanks

**Comment by MarWoes** [comment]
Hi,

Sorry for the late reply (for some reason, GitHub stopped sending me issue notifications). You should use the regular human reference genome. wg-blimp will then build a bisulfitated reference automatically (using bwa-meth).

**Comment by MarWoes** [comment]
Closed for inactivity. Feel free to reopen if there is any issue!
